# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-jk2A7W5FJZvu-bGeOIjFFcguNwK1BGR

Name : Lakshita Aggarwal
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import numpy as np

class PrunableLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super(PrunableLinear, self).__init__()
        self.weight = nn.Parameter(torch.Tensor(out_features, in_features))
        self.bias = nn.Parameter(torch.Tensor(out_features))
        self.gate_scores = nn.Parameter(torch.Tensor(out_features, in_features))

        nn.init.kaiming_uniform_(self.weight, a=np.sqrt(5))
        nn.init.constant_(self.bias, 0)
        nn.init.constant_(self.gate_scores, 1.0)

    def forward(self, x):
        gates = torch.sigmoid(self.gate_scores)
        pruned_weights = self.weight * gates
        return nn.functional.linear(x, pruned_weights, self.bias)

class PruningNet(nn.Module):
    def __init__(self):
        super(PruningNet, self).__init__()
        self.flatten = nn.Flatten()
        self.fc1 = PrunableLinear(32 * 32 * 3, 512)
        self.fc2 = PrunableLinear(512, 256)
        self.fc3 = PrunableLinear(256, 10)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.flatten(x)
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def get_gates(self):
        return [torch.sigmoid(self.fc1.gate_scores),
                torch.sigmoid(self.fc2.gate_scores),
                torch.sigmoid(self.fc3.gate_scores)]

def train_and_eval(lambd, epochs=5):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = PruningNet().to(device)
    optimizer = optim.Adam(model.parameters(), lr=1e-3)
    criterion = nn.CrossEntropyLoss()

    transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])
    trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
    trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

    for epoch in range(epochs):
        for inputs, labels in trainloader:
            inputs, labels = inputs.to(device), labels.to(device)
            optimizer.zero_grad()

            outputs = model(inputs)
            class_loss = criterion(outputs, labels)

            sparsity_loss = sum([torch.sum(torch.abs(g)) for g in model.get_gates()])
            total_loss = class_loss + lambd * sparsity_loss

            total_loss.backward()
            optimizer.step()

    model.eval()
    all_gates = torch.cat([g.flatten() for g in model.get_gates()])
    sparsity = (all_gates < 1e-2).float().mean().item() * 100

    return sparsity, model, all_gates.cpu().detach().numpy()

if __name__ == "__main__":
    lambdas = [1e-5, 1e-4, 1e-3]
    results = []

    print(f"{'Lambda':<10} | {'Sparsity (%)':<15} | {'Status'}")
    print("-" * 40)

    for l in lambdas:
        sparsity, model, gate_values = train_and_eval(l, epochs=1)
        results.append((l, sparsity, gate_values))
        print(f"{l:<10} | {sparsity:<15.2f} | Completed")

    best_lambda, best_sparsity, best_gates = results[1]
    plt.figure(figsize=(10, 6))
    plt.hist(best_gates, bins=50, color='skyblue', edgecolor='black')
    plt.title(f"Gate Value Distribution (Lambda={best_lambda})")
    plt.xlabel("Gate Value (Sigmoid Output)")
    plt.ylabel("Frequency")
    plt.grid(axis='y', alpha=0.75)
    plt.show()